### ISSUE TITLE
Servicenow Pack: TypeError: __init__() got an unexpected keyword argument 'default_payload'

### ISSUE THREAD

**Issue by aksharbarot** [StackStorm-Exchange/stackstorm-servicenow#5]
result:
  exit_code: 1
  result: None
  stderr: "Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 259, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 154, in run
    action = self._get_action_instance()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 229, in _get_action_instance
    action_service=action_service)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/utils.py", line 81, in get_action_class_instance
    action_instance = action_cls(**kwargs)
  File "/opt/stackstorm/packs/servicenow/actions/lib/actions.py", line 8, in __init__
    self.client = self._get_client()
  File "/opt/stackstorm/packs/servicenow/actions/lib/actions.py", line 17, in _get_client
    return sn.Client(instance_name, username, password, default_payload=default_payload)
TypeError: __init__() got an unexpected keyword argument 'default_payload'
"
  stdout: ''

**Comment by nmaludy** [comment]
Can you please post the full `st2 run` command or mistral task statement that you're using to create this error?

**Comment by aksharbarot** [comment]
[root@testbot servicenow]# st2 run servicenow.assign_incident_to number=TEST1501232 name='Axar Barot'
..
id: 5a3d28b180b6f908f5a4
action.ref: servicenow.assign_incident_to
parameters:
  name: Axar Barot
  number: TEST1501232
status: failed
error: Failed rendering value for publish parameter "user_id" in task "getUser" (template string={{getUser.result[0].sys_id}}): 'unicode object' has no attribute 'sys_id'
traceback:   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/container/base.py", line 102, in _do_run
    (status, result, context) = runner.run(action_params)
  File "/opt/stackstorm/runners/action_chain_runner/action_chain_runner.py", line 386, in run
    chain_vars=self.chain_holder.vars)
  File "/opt/stackstorm/runners/action_chain_runner/action_chain_runner.py", line 502, in _render_publish_vars
    raise ParameterRenderingFailedException(msg)

start_timestamp: 2017-12-22T15:45:53.629677Z
end_timestamp: 2017-12-22T15:45:56.076554Z
+--------------------------+---------------------+---------+-------------------------------+-------------------------------+
| id                       | status              | task    | action                        | start_timestamp               |
+--------------------------+---------------------+---------+-------------------------------+-------------------------------+
| 5a3d28b13804e80e2eac5 | failed (2s elapsed) | getUser | servicenow.get_non_structured | Fri, 22 Dec 2017 15:45:53 UTC |
+--------------------------+---------------------+---------+-------------------------------+-------------------------------+
[root@testbot servicenow]# st2 execution get 5a3d28b13804e80e2eac5
id: 5a3d28b13804e80e2eac5
status: failed (2s elapsed)
parameters:
  query: user_name=Axar Barot
  table: sys_user
result:
  exit_code: 1
  result: None
  stderr: "Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 259, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 154, in run
    action = self._get_action_instance()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 229, in _get_action_instance
    action_service=action_service)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/utils.py", line 81, in get_action_class_instance
    action_instance = action_cls(**kwargs)
  File "/opt/stackstorm/packs/servicenow/actions/lib/actions.py", line 8, in __init__
    self.client = self._get_client()
  File "/opt/stackstorm/packs/servicenow/actions/lib/actions.py", line 17, in _get_client
    return sn.Client(instance_name, username, password, default_payload=default_payload)
TypeError: __init__() got an unexpected keyword argument 'default_payload'
"
  stdout: ''

**Comment by nmaludy** [comment]
Looks like the underlying pysnow library changed it's interface. We'll have to upgrade the pack code to match, or pin the pysnow version to a release before the breaking change (i haven't tracked down the exact version yet).

**Comment by nmaludy** [comment]
Looks like the last compatible version with our code is 0.4.10

The breaking change was made in version 0.5.0

**Comment by aksharbarot** [comment]
okay! I have below version.

[root@testbot ~]# pip show pysnow
Name: pysnow
**Version: 0.6.3**
Summary: Python library for the ServiceNow REST API
Home-page: https://github.com/rbw0/pysnow
Location: /usr/lib/python2.7/site-packages
Requires: requests-oauthlib, oauthlib, ijson, six, httpretty, requests

**Comment by namachieli** [comment]
I am also running into this issue, similar outputs from logs. Looks like same issue for me.

**Comment by jamie-owen** [comment]
I noticed this myself, so I forked this repo and made some initial changes in [this](https://github.com/jamie-owen/stackstorm-servicenow/commit/3f9035bb73fb3ba5ea8559e7328a7c35e32877f0) commit. In our case this was enough to get it working, our ServiceNow instance is running Jakarta.

You might still notice some warnings, and I haven't tested all actions since I was only interested in a subset of the pack.

**Comment by nmaludy** [comment]
@jamie-owen would you mind creating a PR? that might facilitate this getting fixed sooner rather than later.

**Comment by jamie-owen** [comment]
Sure, PR here #6.

**Comment by LindsayHill** [comment]
Fixed by https://github.com/StackStorm-Exchange/stackstorm-servicenow/pull/6
